#!/bin/sh
make ready
../../tools/run/matplc -g
#if [ -x ../../mmi/kbd/linuxkbd ]
#then
#  ../../mmi/kbd/linuxkbd --PLCmodule=Kbd
#else
  ./kbd --PLCmodule=Kbd
#fi

# clean up after the vitrine (just in case, shouldn't be necessary)
clear
reset
