daemon_util.o Makefile.depend: daemon_util.c daemon_util.h
mutex_util.o Makefile.depend: mutex_util.c mutex_util.h
sem_util.o Makefile.depend: sem_util.c sem_util.h
shmem_util.o Makefile.depend: shmem_util.c shmem_util.h
signal_util.o Makefile.depend: signal_util.c signal_util.h
sin_util.o Makefile.depend: sin_util.c sin_util.h
string_util.o Makefile.depend: string_util.c ../types.h
timer_util.o Makefile.depend: timer_util.c timer_util.h
