#!/bin/sh
cp -f simple.conf matplc.conf
../../../tools/run/matplc -g
../../../tools/run/handler -c tcpip.cmd &
../../../tools/run/handler -c echo_simple.cmd
../../../tools/run/matplc -s
#../../lib/ipcclean > /dev/null
