#!/bin/sh
../../../tools/run/matplc -g
../../../tools/run/handler -c tcpip.cmd &
../../../tools/run/handler -c matd.cmd &
../../../tools/run/handler -c ladder.cmd &
appletviewer hmilocal.html
#netscape hmilocal.html
#mozilla file:./hmilocal.html
../../../tools/run/matplc -s
#../../lib/ipcclean > /dev/null
