#!/bin/sh
cp -f advanced.conf matplc.conf
../../../tools/run/matplc -g
../../../tools/run/handler -c rs232c.cmd &
../../../tools/run/handler -c echo_advanced.cmd
../../../tools/run/matplc -s
#../../lib/ipcclean > /dev/null
