/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_top_level (void)
{
  GtkWidget *top_level;
  GtkWidget *alignment1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *load1;
  GtkWidget *save1;
  GtkWidget *separator2;
  GtkWidget *exit1;
  GtkWidget *add1;
  GtkWidget *add1_menu;
  GtkAccelGroup *add1_menu_accels;
  GtkWidget *modules1;
  GtkWidget *elements1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *about1;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow10;
  GtkWidget *module_list;
  GtkWidget *eventbox1;
  GtkWidget *module_name_label;
  GtkWidget *eventbox2;
  GtkWidget *module_path_label;
  GtkWidget *eventbox3;
  GtkWidget *module_parameters_label;
  GtkWidget *module_tab;
  GtkWidget *element_list;
  GtkWidget *id_eventbox;
  GtkWidget *ID_label;
  GtkWidget *description_eventbox;
  GtkWidget *Description_label;
  GtkWidget *owner_eventbox;
  GtkWidget *Owner_label;
  GtkWidget *mem_location_eventbox;
  GtkWidget *Location_label;
  GtkWidget *init_value_eventbox;
  GtkWidget *Init_label;
  GtkWidget *bits_eventbox;
  GtkWidget *Bits_label;
  GtkWidget *point_type_eventbox;
  GtkWidget *Type_label;
  GtkWidget *point_tab;
  GtkWidget *label169;
  GtkWidget *synch_tab;
  GtkWidget *label175;
  GtkWidget *other_tab;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  top_level = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (top_level, "top_level");
  gtk_object_set_data (GTK_OBJECT (top_level), "top_level", top_level);
  gtk_widget_set_uposition (top_level, 20, 100);
  gtk_widget_set_usize (top_level, 800, 600);
  gtk_window_set_title (GTK_WINDOW (top_level), _("MatPLC.conf Point Table Editor"));

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_ref (alignment1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "alignment1", alignment1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (top_level), alignment1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file1)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (file1, "file1");
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_set_name (file1_menu, "file1_menu");
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  load1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (load1)->child),
                                   _("_Load"));
  gtk_widget_add_accelerator (load1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (load1, "load1");
  gtk_widget_ref (load1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "load1", load1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (load1);
  gtk_container_add (GTK_CONTAINER (file1_menu), load1);

  save1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (save1)->child),
                                   _("_Save"));
  gtk_widget_add_accelerator (save1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (save1, "save1");
  gtk_widget_ref (save1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "save1", save1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (file1_menu), save1);

  separator2 = gtk_menu_item_new ();
  gtk_widget_set_name (separator2, "separator2");
  gtk_widget_ref (separator2);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "separator2", separator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator2);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator2);
  gtk_widget_set_sensitive (separator2, FALSE);

  exit1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit1)->child),
                                   _("E_xit"));
  gtk_widget_add_accelerator (exit1, "activate_item", file1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (exit1, "exit1");
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), exit1);

  add1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (add1)->child),
                                   _("_Add"));
  gtk_widget_add_accelerator (add1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (add1, "add1");
  gtk_widget_ref (add1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "add1", add1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add1);
  gtk_container_add (GTK_CONTAINER (menubar1), add1);

  add1_menu = gtk_menu_new ();
  gtk_widget_set_name (add1_menu, "add1_menu");
  gtk_widget_ref (add1_menu);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "add1_menu", add1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (add1), add1_menu);
  add1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (add1_menu));

  modules1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (modules1)->child),
                                   _("_Modules"));
  gtk_widget_add_accelerator (modules1, "activate_item", add1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (modules1, "modules1");
  gtk_widget_ref (modules1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "modules1", modules1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (modules1);
  gtk_container_add (GTK_CONTAINER (add1_menu), modules1);

  elements1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (elements1)->child),
                                   _("_Points"));
  gtk_widget_add_accelerator (elements1, "activate_item", add1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (elements1, "elements1");
  gtk_widget_ref (elements1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "elements1", elements1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (elements1);
  gtk_container_add (GTK_CONTAINER (add1_menu), elements1);

  help1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help1)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help1, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_set_name (help1, "help1");
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (menubar1), help1);

  help1_menu = gtk_menu_new ();
  gtk_widget_set_name (help1_menu, "help1_menu");
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  about1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about1)->child),
                                   _("_About"));
  gtk_widget_add_accelerator (about1, "activate_item", help1_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_set_name (about1, "about1");
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  scrolledwindow10 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow10, "scrolledwindow10");
  gtk_widget_ref (scrolledwindow10);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "scrolledwindow10", scrolledwindow10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow10);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow10);

  module_list = gtk_clist_new (3);
  gtk_widget_set_name (module_list, "module_list");
  gtk_widget_ref (module_list);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "module_list", module_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow10), module_list);
  gtk_clist_set_column_width (GTK_CLIST (module_list), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (module_list), 1, 290);
  gtk_clist_set_column_width (GTK_CLIST (module_list), 2, 80);
  gtk_clist_column_titles_show (GTK_CLIST (module_list));

  eventbox1 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox1, "eventbox1");
  gtk_widget_ref (eventbox1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "eventbox1", eventbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (eventbox1);
  gtk_clist_set_column_widget (GTK_CLIST (module_list), 0, eventbox1);

  module_name_label = gtk_label_new (_("Module Name"));
  gtk_widget_set_name (module_name_label, "module_name_label");
  gtk_widget_ref (module_name_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "module_name_label", module_name_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_name_label);
  gtk_container_add (GTK_CONTAINER (eventbox1), module_name_label);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox2, "eventbox2");
  gtk_widget_ref (eventbox2);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "eventbox2", eventbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (eventbox2);
  gtk_clist_set_column_widget (GTK_CLIST (module_list), 1, eventbox2);

  module_path_label = gtk_label_new (_("Path"));
  gtk_widget_set_name (module_path_label, "module_path_label");
  gtk_widget_ref (module_path_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "module_path_label", module_path_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_path_label);
  gtk_container_add (GTK_CONTAINER (eventbox2), module_path_label);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_set_name (eventbox3, "eventbox3");
  gtk_widget_ref (eventbox3);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "eventbox3", eventbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (eventbox3);
  gtk_clist_set_column_widget (GTK_CLIST (module_list), 2, eventbox3);

  module_parameters_label = gtk_label_new (_("Additional Parameters"));
  gtk_widget_set_name (module_parameters_label, "module_parameters_label");
  gtk_widget_ref (module_parameters_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "module_parameters_label", module_parameters_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_parameters_label);
  gtk_container_add (GTK_CONTAINER (eventbox3), module_parameters_label);

  module_tab = gtk_label_new (_("Module Definition"));
  gtk_widget_set_name (module_tab, "module_tab");
  gtk_widget_ref (module_tab);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "module_tab", module_tab,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_tab);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), module_tab);

  element_list = gtk_clist_new (7);
  gtk_widget_set_name (element_list, "element_list");
  gtk_widget_ref (element_list);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "element_list", element_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (element_list);
  gtk_container_add (GTK_CONTAINER (notebook1), element_list);
  gtk_clist_set_column_width (GTK_CLIST (element_list), 0, 97);
  gtk_clist_set_column_width (GTK_CLIST (element_list), 1, 284);
  gtk_clist_set_column_width (GTK_CLIST (element_list), 2, 87);
  gtk_clist_set_column_width (GTK_CLIST (element_list), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (element_list), 4, 69);
  gtk_clist_set_column_width (GTK_CLIST (element_list), 5, 29);
  gtk_clist_set_column_width (GTK_CLIST (element_list), 6, 80);
  gtk_clist_column_titles_show (GTK_CLIST (element_list));

  id_eventbox = gtk_event_box_new ();
  gtk_widget_set_name (id_eventbox, "id_eventbox");
  gtk_widget_ref (id_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "id_eventbox", id_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (id_eventbox);
  gtk_clist_set_column_widget (GTK_CLIST (element_list), 0, id_eventbox);

  ID_label = gtk_label_new (_("ID"));
  gtk_widget_set_name (ID_label, "ID_label");
  gtk_widget_ref (ID_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "ID_label", ID_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ID_label);
  gtk_container_add (GTK_CONTAINER (id_eventbox), ID_label);

  description_eventbox = gtk_event_box_new ();
  gtk_widget_set_name (description_eventbox, "description_eventbox");
  gtk_widget_ref (description_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "description_eventbox", description_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (description_eventbox);
  gtk_clist_set_column_widget (GTK_CLIST (element_list), 1, description_eventbox);

  Description_label = gtk_label_new (_("Description"));
  gtk_widget_set_name (Description_label, "Description_label");
  gtk_widget_ref (Description_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "Description_label", Description_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Description_label);
  gtk_container_add (GTK_CONTAINER (description_eventbox), Description_label);

  owner_eventbox = gtk_event_box_new ();
  gtk_widget_set_name (owner_eventbox, "owner_eventbox");
  gtk_widget_ref (owner_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "owner_eventbox", owner_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (owner_eventbox);
  gtk_clist_set_column_widget (GTK_CLIST (element_list), 2, owner_eventbox);

  Owner_label = gtk_label_new (_("Owner"));
  gtk_widget_set_name (Owner_label, "Owner_label");
  gtk_widget_ref (Owner_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "Owner_label", Owner_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Owner_label);
  gtk_container_add (GTK_CONTAINER (owner_eventbox), Owner_label);

  mem_location_eventbox = gtk_event_box_new ();
  gtk_widget_set_name (mem_location_eventbox, "mem_location_eventbox");
  gtk_widget_ref (mem_location_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "mem_location_eventbox", mem_location_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (mem_location_eventbox);
  gtk_clist_set_column_widget (GTK_CLIST (element_list), 3, mem_location_eventbox);

  Location_label = gtk_label_new (_("[Mem Location]"));
  gtk_widget_set_name (Location_label, "Location_label");
  gtk_widget_ref (Location_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "Location_label", Location_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Location_label);
  gtk_container_add (GTK_CONTAINER (mem_location_eventbox), Location_label);

  init_value_eventbox = gtk_event_box_new ();
  gtk_widget_set_name (init_value_eventbox, "init_value_eventbox");
  gtk_widget_ref (init_value_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "init_value_eventbox", init_value_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (init_value_eventbox);
  gtk_clist_set_column_widget (GTK_CLIST (element_list), 4, init_value_eventbox);

  Init_label = gtk_label_new (_("[Init Value]"));
  gtk_widget_set_name (Init_label, "Init_label");
  gtk_widget_ref (Init_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "Init_label", Init_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Init_label);
  gtk_container_add (GTK_CONTAINER (init_value_eventbox), Init_label);

  bits_eventbox = gtk_event_box_new ();
  gtk_widget_set_name (bits_eventbox, "bits_eventbox");
  gtk_widget_ref (bits_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "bits_eventbox", bits_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bits_eventbox);
  gtk_clist_set_column_widget (GTK_CLIST (element_list), 5, bits_eventbox);

  Bits_label = gtk_label_new (_("Bits"));
  gtk_widget_set_name (Bits_label, "Bits_label");
  gtk_widget_ref (Bits_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "Bits_label", Bits_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bits_label);
  gtk_container_add (GTK_CONTAINER (bits_eventbox), Bits_label);

  point_type_eventbox = gtk_event_box_new ();
  gtk_widget_set_name (point_type_eventbox, "point_type_eventbox");
  gtk_widget_ref (point_type_eventbox);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "point_type_eventbox", point_type_eventbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (point_type_eventbox);
  gtk_clist_set_column_widget (GTK_CLIST (element_list), 6, point_type_eventbox);

  Type_label = gtk_label_new (_("Point Type"));
  gtk_widget_set_name (Type_label, "Type_label");
  gtk_widget_ref (Type_label);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "Type_label", Type_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Type_label);
  gtk_container_add (GTK_CONTAINER (point_type_eventbox), Type_label);

  point_tab = gtk_label_new (_("Point Definition"));
  gtk_widget_set_name (point_tab, "point_tab");
  gtk_widget_ref (point_tab);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "point_tab", point_tab,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (point_tab);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), point_tab);

  label169 = gtk_label_new (_("Not Yet Implemented......."));
  gtk_widget_set_name (label169, "label169");
  gtk_widget_ref (label169);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "label169", label169,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label169);
  gtk_container_add (GTK_CONTAINER (notebook1), label169);

  synch_tab = gtk_label_new (_("Synchronization"));
  gtk_widget_set_name (synch_tab, "synch_tab");
  gtk_widget_ref (synch_tab);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "synch_tab", synch_tab,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (synch_tab);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), synch_tab);

  label175 = gtk_label_new (_("Not Yet Implemented....."));
  gtk_widget_set_name (label175, "label175");
  gtk_widget_ref (label175);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "label175", label175,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label175);
  gtk_container_add (GTK_CONTAINER (notebook1), label175);

  other_tab = gtk_label_new (_("Module Specific Definitions"));
  gtk_widget_set_name (other_tab, "other_tab");
  gtk_widget_ref (other_tab);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "other_tab", other_tab,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (other_tab);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), other_tab);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar1, "statusbar1");
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (top_level), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (top_level), "show",
                      GTK_SIGNAL_FUNC (on_window1_show),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (top_level), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (load1), "activate",
                      GTK_SIGNAL_FUNC (on_load1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (save1), "activate",
                      GTK_SIGNAL_FUNC (on_save1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (modules1), "activate",
                      GTK_SIGNAL_FUNC (on_add_modules_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (elements1), "activate",
                      GTK_SIGNAL_FUNC (on_elements1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (module_list), "button_press_event",
                      GTK_SIGNAL_FUNC (on_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (module_list), "select_row",
                      GTK_SIGNAL_FUNC (on_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (element_list), "button_press_event",
                      GTK_SIGNAL_FUNC (on_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (element_list), "select_row",
                      GTK_SIGNAL_FUNC (on_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (id_eventbox), "button_press_event",
                      GTK_SIGNAL_FUNC (on_column_clicked),
                      0);
  gtk_signal_connect (GTK_OBJECT (description_eventbox), "button_press_event",
                      GTK_SIGNAL_FUNC (on_column_clicked),
                      1);
  gtk_signal_connect (GTK_OBJECT (owner_eventbox), "button_press_event",
                      GTK_SIGNAL_FUNC (on_column_clicked),
                      2);
  gtk_signal_connect (GTK_OBJECT (mem_location_eventbox), "button_press_event",
                      GTK_SIGNAL_FUNC (on_column_clicked),
                      3);
  gtk_signal_connect (GTK_OBJECT (init_value_eventbox), "button_press_event",
                      GTK_SIGNAL_FUNC (on_column_clicked),
                      4);
  gtk_signal_connect (GTK_OBJECT (bits_eventbox), "button_press_event",
                      GTK_SIGNAL_FUNC (on_column_clicked),
                      5);
  gtk_signal_connect (GTK_OBJECT (point_type_eventbox), "button_press_event",
                      GTK_SIGNAL_FUNC (on_column_clicked),
                      6);

  gtk_window_add_accel_group (GTK_WINDOW (top_level), accel_group);

  return top_level;
}

GtkWidget*
create_About (void)
{
  GtkWidget *About;
  GtkWidget *table1;
  GtkWidget *button3;
  GtkWidget *label54;
  GtkWidget *scrolledwindow9;
  GtkWidget *text2;

  About = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (About, "About");
  gtk_object_set_data (GTK_OBJECT (About), "About", About);
  gtk_window_set_title (GTK_WINDOW (About), _("About..."));
  gtk_window_set_position (GTK_WINDOW (About), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (About), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (About), 300, -1);

  table1 = gtk_table_new (5, 3, TRUE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (About), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (About), table1);

  button3 = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (button3, "button3");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (About), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_table_attach (GTK_TABLE (table1), button3, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 10);
  gtk_widget_set_usize (button3, 102, 34);
  gtk_container_set_border_width (GTK_CONTAINER (button3), 2);

  label54 = gtk_label_new (_("Config Edit"));
  gtk_widget_set_name (label54, "label54");
  gtk_widget_ref (label54);
  gtk_object_set_data_full (GTK_OBJECT (About), "label54", label54,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table1), label54, 0, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (label54, -2, 26);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow9, "scrolledwindow9");
  gtk_widget_ref (scrolledwindow9);
  gtk_object_set_data_full (GTK_OBJECT (About), "scrolledwindow9", scrolledwindow9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow9);
  gtk_table_attach (GTK_TABLE (table1), scrolledwindow9, 0, 3, 1, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_usize (scrolledwindow9, 500, -2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  text2 = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (text2, "text2");
  gtk_widget_ref (text2);
  gtk_object_set_data_full (GTK_OBJECT (About), "text2", text2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), text2);
  gtk_text_insert (GTK_TEXT (text2), NULL, NULL, NULL,
                   _("MatPLC Configuration File Editor\n\nCopyright (c) 2002 by Joe Jansen\n\n\n    This program is free software; you can redistribute it and/or modify\n    it under the terms of the GNU General Public License as published by\n    the Free Software Foundation; either version 2 of the License, or\n    (at your option) any later version.\n\n    This program is distributed in the hope that it will be useful,\n    but WITHOUT ANY WARRANTY; without even the implied warranty of\n    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n    GNU General Public License for more details.\n\n    You should have received a copy of the GNU General Public License\n    along with this program; if not, write to the Free Software\n    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA\n"), 795);

  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_button3_clicked),
                      NULL);

  return About;
}

GtkWidget*
create_Add_Element (void)
{
  GtkWidget *Add_Element;
  GtkWidget *table2;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *Close_Add_Element;
  GtkWidget *label60;
  GtkWidget *Add_Element_Help;
  GtkWidget *Add_Element_Button;
  GtkWidget *label64;
  GtkWidget *label66;
  GtkWidget *edit_entry1;
  GtkWidget *edit_entry2;
  GtkWidget *edit_entry4;
  GtkWidget *edit_entry5;
  GtkWidget *edit_entry6;
  GtkWidget *label120;
  GSList *type_group = NULL;
  GtkWidget *unsigned_button;
  GtkWidget *integer_button;
  GtkWidget *binary_button;
  GtkWidget *float_button;
  GtkWidget *other_button;
  GtkWidget *owner_menu;
  GList *owner_menu_items = NULL;
  GtkWidget *edit_entry3;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  Add_Element = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (Add_Element, "Add_Element");
  gtk_object_set_data (GTK_OBJECT (Add_Element), "Add_Element", Add_Element);
  gtk_window_set_title (GTK_WINDOW (Add_Element), _("Add Element"));
  gtk_window_set_position (GTK_WINDOW (Add_Element), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (Add_Element), TRUE);
  gtk_window_set_policy (GTK_WINDOW (Add_Element), TRUE, TRUE, FALSE);

  table2 = gtk_table_new (7, 3, FALSE);
  gtk_widget_set_name (table2, "table2");
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (Add_Element), table2);

  label61 = gtk_label_new (_("Description"));
  gtk_widget_set_name (label61, "label61");
  gtk_widget_ref (label61);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "label61", label61,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table2), label61, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label61), 0, 0.5);

  label62 = gtk_label_new (_("Owner"));
  gtk_widget_set_name (label62, "label62");
  gtk_widget_ref (label62);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "label62", label62,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table2), label62, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label62), 0, 0.5);

  label63 = gtk_label_new (_("Memory Location"));
  gtk_widget_set_name (label63, "label63");
  gtk_widget_ref (label63);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "label63", label63,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table2), label63, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label63), 0, 0.5);

  Close_Add_Element = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (Close_Add_Element, "Close_Add_Element");
  gtk_widget_ref (Close_Add_Element);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "Close_Add_Element", Close_Add_Element,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Close_Add_Element);
  gtk_table_attach (GTK_TABLE (table2), Close_Add_Element, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 100, 0);
  gtk_container_set_border_width (GTK_CONTAINER (Close_Add_Element), 10);

  label60 = gtk_label_new (_("ID (Name)"));
  gtk_widget_set_name (label60, "label60");
  gtk_widget_ref (label60);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "label60", label60,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label60);
  gtk_table_attach (GTK_TABLE (table2), label60, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label60), 0, 0.5);

  Add_Element_Help = gtk_button_new_with_label (_("HELP"));
  gtk_widget_set_name (Add_Element_Help, "Add_Element_Help");
  gtk_widget_ref (Add_Element_Help);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "Add_Element_Help", Add_Element_Help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Add_Element_Help);
  gtk_table_attach (GTK_TABLE (table2), Add_Element_Help, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 9, 0);

  Add_Element_Button = gtk_button_new_with_label (_("ADD"));
  gtk_widget_set_name (Add_Element_Button, "Add_Element_Button");
  gtk_widget_ref (Add_Element_Button);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "Add_Element_Button", Add_Element_Button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Add_Element_Button);
  gtk_table_attach (GTK_TABLE (table2), Add_Element_Button, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (Add_Element_Button), 10);
  GTK_WIDGET_SET_FLAGS (Add_Element_Button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (Add_Element_Button, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  label64 = gtk_label_new (_("Initial State"));
  gtk_widget_set_name (label64, "label64");
  gtk_widget_ref (label64);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "label64", label64,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label64);
  gtk_table_attach (GTK_TABLE (table2), label64, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label64), 0, 0.5);

  label66 = gtk_label_new (_("Bit Width"));
  gtk_widget_set_name (label66, "label66");
  gtk_widget_ref (label66);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "label66", label66,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label66);
  gtk_table_attach (GTK_TABLE (table2), label66, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label66), 0, 0.5);

  edit_entry1 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry1, "edit_entry1");
  gtk_widget_ref (edit_entry1);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "edit_entry1", edit_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry1);
  gtk_table_attach (GTK_TABLE (table2), edit_entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (edit_entry1, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, edit_entry1, _("Name used by PLC modules"), NULL);

  edit_entry2 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry2, "edit_entry2");
  gtk_widget_ref (edit_entry2);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "edit_entry2", edit_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry2);
  gtk_table_attach (GTK_TABLE (table2), edit_entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry2, _("Description of this point"), NULL);

  edit_entry4 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry4, "edit_entry4");
  gtk_widget_ref (edit_entry4);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "edit_entry4", edit_entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry4);
  gtk_table_attach (GTK_TABLE (table2), edit_entry4, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry4, _("Optional : map this point in memory"), NULL);

  edit_entry5 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry5, "edit_entry5");
  gtk_widget_ref (edit_entry5);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "edit_entry5", edit_entry5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry5);
  gtk_table_attach (GTK_TABLE (table2), edit_entry5, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry5, _("Optional:  Initial state of this bit on startup"), NULL);

  edit_entry6 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry6, "edit_entry6");
  gtk_widget_ref (edit_entry6);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "edit_entry6", edit_entry6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry6);
  gtk_table_attach (GTK_TABLE (table2), edit_entry6, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry6, _("Number of Bits (up to 32) for this register.  Binary can only be 1."), NULL);

  label120 = gtk_label_new (_("Point Type"));
  gtk_widget_set_name (label120, "label120");
  gtk_widget_ref (label120);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "label120", label120,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label120);
  gtk_table_attach (GTK_TABLE (table2), label120, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label120), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label120), 9, 0);

  unsigned_button = gtk_radio_button_new_with_label (type_group, _("Unsigned"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (unsigned_button));
  gtk_widget_set_name (unsigned_button, "unsigned_button");
  gtk_widget_ref (unsigned_button);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "unsigned_button", unsigned_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (unsigned_button);
  gtk_table_attach (GTK_TABLE (table2), unsigned_button, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (unsigned_button, GTK_CAN_FOCUS);

  integer_button = gtk_radio_button_new_with_label (type_group, _("Integer"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (integer_button));
  gtk_widget_set_name (integer_button, "integer_button");
  gtk_widget_ref (integer_button);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "integer_button", integer_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (integer_button);
  gtk_table_attach (GTK_TABLE (table2), integer_button, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (integer_button, GTK_CAN_FOCUS);

  binary_button = gtk_radio_button_new_with_label (type_group, _("Binary"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (binary_button));
  gtk_widget_set_name (binary_button, "binary_button");
  gtk_widget_ref (binary_button);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "binary_button", binary_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (binary_button);
  gtk_table_attach (GTK_TABLE (table2), binary_button, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (binary_button, GTK_CAN_FOCUS);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (binary_button), TRUE);

  float_button = gtk_radio_button_new_with_label (type_group, _("Float"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (float_button));
  gtk_widget_set_name (float_button, "float_button");
  gtk_widget_ref (float_button);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "float_button", float_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (float_button);
  gtk_table_attach (GTK_TABLE (table2), float_button, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (float_button, GTK_CAN_FOCUS);

  other_button = gtk_radio_button_new_with_label (type_group, _("Other"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (other_button));
  gtk_widget_set_name (other_button, "other_button");
  gtk_widget_ref (other_button);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "other_button", other_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (other_button);
  gtk_table_attach (GTK_TABLE (table2), other_button, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (other_button, GTK_CAN_FOCUS);

  owner_menu = gtk_combo_new ();
  gtk_widget_set_name (owner_menu, "owner_menu");
  gtk_widget_ref (owner_menu);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "owner_menu", owner_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (owner_menu);
  gtk_table_attach (GTK_TABLE (table2), owner_menu, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (owner_menu), TRUE, FALSE);
  owner_menu_items = g_list_append (owner_menu_items, (gpointer) _("item1"));
  owner_menu_items = g_list_append (owner_menu_items, (gpointer) _("item2"));
  owner_menu_items = g_list_append (owner_menu_items, (gpointer) _("item3"));
  gtk_combo_set_popdown_strings (GTK_COMBO (owner_menu), owner_menu_items);
  g_list_free (owner_menu_items);

  edit_entry3 = GTK_COMBO (owner_menu)->entry;
  gtk_widget_set_name (edit_entry3, "edit_entry3");
  gtk_widget_ref (edit_entry3);
  gtk_object_set_data_full (GTK_OBJECT (Add_Element), "edit_entry3", edit_entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry3);
  gtk_entry_set_text (GTK_ENTRY (edit_entry3), _("item3"));

  gtk_signal_connect (GTK_OBJECT (Close_Add_Element), "clicked",
                      GTK_SIGNAL_FUNC (on_Close_Binary_Add_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Add_Element_Button), "clicked",
                      GTK_SIGNAL_FUNC (on_Add_Element_Button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry1), "key_press_event",
                      GTK_SIGNAL_FUNC (on_Add_Element_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry2), "key_press_event",
                      GTK_SIGNAL_FUNC (on_Add_Element_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry4), "key_press_event",
                      GTK_SIGNAL_FUNC (on_Add_Element_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry5), "key_press_event",
                      GTK_SIGNAL_FUNC (on_Add_Element_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry6), "key_press_event",
                      GTK_SIGNAL_FUNC (on_Add_Element_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (unsigned_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Unsigned_Button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (integer_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Integer_Button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (binary_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Binary_Button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (float_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Float_Button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (other_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Other_Button_toggled),
                      NULL);

  gtk_widget_grab_focus (edit_entry1);
  gtk_widget_grab_default (edit_entry1);
  gtk_object_set_data (GTK_OBJECT (Add_Element), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (Add_Element), accel_group);

  return Add_Element;
}

GtkWidget*
create_reuse_error (void)
{
  GtkWidget *reuse_error;
  GtkWidget *vbox2;
  GtkWidget *error_text;
  GtkWidget *button9;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  reuse_error = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (reuse_error, "reuse_error");
  gtk_object_set_data (GTK_OBJECT (reuse_error), "reuse_error", reuse_error);
  gtk_widget_set_usize (reuse_error, 300, 80);
  gtk_window_set_title (GTK_WINDOW (reuse_error), _("Error Message"));
  gtk_window_set_position (GTK_WINDOW (reuse_error), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (reuse_error), TRUE);
  gtk_window_set_policy (GTK_WINDOW (reuse_error), FALSE, FALSE, FALSE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (reuse_error), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (reuse_error), vbox2);

  error_text = gtk_label_new (_("Item names cannot be re-used"));
  gtk_widget_set_name (error_text, "error_text");
  gtk_widget_ref (error_text);
  gtk_object_set_data_full (GTK_OBJECT (reuse_error), "error_text", error_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (error_text);
  gtk_box_pack_start (GTK_BOX (vbox2), error_text, TRUE, TRUE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (error_text), TRUE);

  button9 = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (button9, "button9");
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (reuse_error), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);
  gtk_box_pack_start (GTK_BOX (vbox2), button9, FALSE, FALSE, 0);
  gtk_widget_add_accelerator (button9, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (on_button9_clicked),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (reuse_error), accel_group);

  return reuse_error;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection1 = gtk_file_selection_new (_("Select File"));
  gtk_widget_set_name (fileselection1, "fileselection1");
  gtk_object_set_data (GTK_OBJECT (fileselection1), "fileselection1", fileselection1);
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  gtk_window_set_modal (GTK_WINDOW (fileselection1), TRUE);

  ok_button1 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_widget_set_name (ok_button1, "ok_button1");
  gtk_object_set_data (GTK_OBJECT (fileselection1), "ok_button1", ok_button1);
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_widget_set_name (cancel_button1, "cancel_button1");
  gtk_object_set_data (GTK_OBJECT (fileselection1), "cancel_button1", cancel_button1);
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (ok_button1), "clicked",
                      GTK_SIGNAL_FUNC (file_select_OK),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (cancel_button1), "clicked",
                      GTK_SIGNAL_FUNC (file_select_cancel),
                      NULL);

  return fileselection1;
}

GtkWidget*
create_Notebook_Popup (void)
{
  GtkWidget *Notebook_Popup;
  GtkAccelGroup *Notebook_Popup_accels;
  GtkWidget *edit1;
  GtkWidget *delete1;

  Notebook_Popup = gtk_menu_new ();
  gtk_widget_set_name (Notebook_Popup, "Notebook_Popup");
  gtk_object_set_data (GTK_OBJECT (Notebook_Popup), "Notebook_Popup", Notebook_Popup);
  Notebook_Popup_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (Notebook_Popup));

  edit1 = gtk_menu_item_new_with_label (_("Edit"));
  gtk_widget_set_name (edit1, "edit1");
  gtk_widget_ref (edit1);
  gtk_object_set_data_full (GTK_OBJECT (Notebook_Popup), "edit1", edit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit1);
  gtk_container_add (GTK_CONTAINER (Notebook_Popup), edit1);

  delete1 = gtk_menu_item_new_with_label (_("Delete"));
  gtk_widget_set_name (delete1, "delete1");
  gtk_widget_ref (delete1);
  gtk_object_set_data_full (GTK_OBJECT (Notebook_Popup), "delete1", delete1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (Notebook_Popup), delete1);

  gtk_signal_connect (GTK_OBJECT (edit1), "activate",
                      GTK_SIGNAL_FUNC (on_edit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (delete1), "activate",
                      GTK_SIGNAL_FUNC (on_delete1_activate),
                      NULL);

  return Notebook_Popup;
}

GtkWidget*
create_edit_entry (void)
{
  GtkWidget *edit_entry;
  GtkWidget *table4;
  GtkWidget *label121;
  GtkWidget *label122;
  GtkWidget *label123;
  GtkWidget *close_edit_element;
  GtkWidget *label124;
  GtkWidget *button11;
  GtkWidget *update_element_button;
  GtkWidget *label125;
  GtkWidget *label126;
  GtkWidget *edit_entry1;
  GtkWidget *edit_entry2;
  GtkWidget *edit_entry3;
  GtkWidget *edit_entry4;
  GtkWidget *edit_entry5;
  GtkWidget *edit_entry6;
  GSList *type_group = NULL;
  GtkWidget *binary_button;
  GtkWidget *integer_button;
  GtkWidget *unsigned_button;
  GtkWidget *float_button;
  GtkWidget *other_button;
  GtkWidget *label161;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  edit_entry = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_widget_set_name (edit_entry, "edit_entry");
  gtk_object_set_data (GTK_OBJECT (edit_entry), "edit_entry", edit_entry);
  gtk_window_set_title (GTK_WINDOW (edit_entry), _("Edit Element"));
  gtk_window_set_position (GTK_WINDOW (edit_entry), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (edit_entry), TRUE);
  gtk_window_set_policy (GTK_WINDOW (edit_entry), TRUE, TRUE, FALSE);

  table4 = gtk_table_new (7, 3, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (edit_entry), table4);

  label121 = gtk_label_new (_("Description"));
  gtk_widget_set_name (label121, "label121");
  gtk_widget_ref (label121);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "label121", label121,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label121);
  gtk_table_attach (GTK_TABLE (table4), label121, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label121), 0, 0.5);

  label122 = gtk_label_new (_("Owner"));
  gtk_widget_set_name (label122, "label122");
  gtk_widget_ref (label122);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "label122", label122,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label122);
  gtk_table_attach (GTK_TABLE (table4), label122, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label122), 0, 0.5);

  label123 = gtk_label_new (_("Memory Location"));
  gtk_widget_set_name (label123, "label123");
  gtk_widget_ref (label123);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "label123", label123,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label123);
  gtk_table_attach (GTK_TABLE (table4), label123, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label123), 0, 0.5);

  close_edit_element = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (close_edit_element, "close_edit_element");
  gtk_widget_ref (close_edit_element);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "close_edit_element", close_edit_element,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close_edit_element);
  gtk_table_attach (GTK_TABLE (table4), close_edit_element, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 100, 0);
  gtk_container_set_border_width (GTK_CONTAINER (close_edit_element), 10);

  label124 = gtk_label_new (_("ID (Name)"));
  gtk_widget_set_name (label124, "label124");
  gtk_widget_ref (label124);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "label124", label124,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label124);
  gtk_table_attach (GTK_TABLE (table4), label124, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label124), 0, 0.5);

  button11 = gtk_button_new_with_label (_("HELP"));
  gtk_widget_set_name (button11, "button11");
  gtk_widget_ref (button11);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "button11", button11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button11);
  gtk_table_attach (GTK_TABLE (table4), button11, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 9, 0);

  update_element_button = gtk_button_new_with_label (_("Update"));
  gtk_widget_set_name (update_element_button, "update_element_button");
  gtk_widget_ref (update_element_button);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "update_element_button", update_element_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (update_element_button);
  gtk_table_attach (GTK_TABLE (table4), update_element_button, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (update_element_button), 10);
  GTK_WIDGET_SET_FLAGS (update_element_button, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (update_element_button, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);

  label125 = gtk_label_new (_("Initial State"));
  gtk_widget_set_name (label125, "label125");
  gtk_widget_ref (label125);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "label125", label125,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label125);
  gtk_table_attach (GTK_TABLE (table4), label125, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label125), 0, 0.5);

  label126 = gtk_label_new (_("Bit Width"));
  gtk_widget_set_name (label126, "label126");
  gtk_widget_ref (label126);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "label126", label126,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label126);
  gtk_table_attach (GTK_TABLE (table4), label126, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label126), 0, 0.5);

  edit_entry1 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry1, "edit_entry1");
  gtk_widget_ref (edit_entry1);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "edit_entry1", edit_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry1);
  gtk_table_attach (GTK_TABLE (table4), edit_entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_SET_FLAGS (edit_entry1, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, edit_entry1, _("Name used by PLC modules"), NULL);

  edit_entry2 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry2, "edit_entry2");
  gtk_widget_ref (edit_entry2);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "edit_entry2", edit_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry2);
  gtk_table_attach (GTK_TABLE (table4), edit_entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry2, _("Description of this point"), NULL);

  edit_entry3 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry3, "edit_entry3");
  gtk_widget_ref (edit_entry3);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "edit_entry3", edit_entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry3);
  gtk_table_attach (GTK_TABLE (table4), edit_entry3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry3, _("Name of module that has write access to this bit"), NULL);

  edit_entry4 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry4, "edit_entry4");
  gtk_widget_ref (edit_entry4);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "edit_entry4", edit_entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry4);
  gtk_table_attach (GTK_TABLE (table4), edit_entry4, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry4, _("Optional : map this point in memory"), NULL);

  edit_entry5 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry5, "edit_entry5");
  gtk_widget_ref (edit_entry5);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "edit_entry5", edit_entry5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry5);
  gtk_table_attach (GTK_TABLE (table4), edit_entry5, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry5, _("Optional:  Initial state of this bit on startup"), NULL);

  edit_entry6 = gtk_entry_new ();
  gtk_widget_set_name (edit_entry6, "edit_entry6");
  gtk_widget_ref (edit_entry6);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "edit_entry6", edit_entry6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (edit_entry6);
  gtk_table_attach (GTK_TABLE (table4), edit_entry6, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, edit_entry6, _("Number of Bits (up to 32) for this register.  Binary can only be 1."), NULL);

  binary_button = gtk_radio_button_new_with_label (type_group, _("Binary"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (binary_button));
  gtk_widget_set_name (binary_button, "binary_button");
  gtk_widget_ref (binary_button);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "binary_button", binary_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (binary_button);
  gtk_table_attach (GTK_TABLE (table4), binary_button, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (binary_button, GTK_CAN_FOCUS);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (binary_button), TRUE);

  integer_button = gtk_radio_button_new_with_label (type_group, _("Integer"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (integer_button));
  gtk_widget_set_name (integer_button, "integer_button");
  gtk_widget_ref (integer_button);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "integer_button", integer_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (integer_button);
  gtk_table_attach (GTK_TABLE (table4), integer_button, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (integer_button, GTK_CAN_FOCUS);

  unsigned_button = gtk_radio_button_new_with_label (type_group, _("Unsigned"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (unsigned_button));
  gtk_widget_set_name (unsigned_button, "unsigned_button");
  gtk_widget_ref (unsigned_button);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "unsigned_button", unsigned_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (unsigned_button);
  gtk_table_attach (GTK_TABLE (table4), unsigned_button, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (unsigned_button, GTK_CAN_FOCUS);

  float_button = gtk_radio_button_new_with_label (type_group, _("Float"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (float_button));
  gtk_widget_set_name (float_button, "float_button");
  gtk_widget_ref (float_button);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "float_button", float_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (float_button);
  gtk_table_attach (GTK_TABLE (table4), float_button, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (float_button, GTK_CAN_FOCUS);

  other_button = gtk_radio_button_new_with_label (type_group, _("Other"));
  type_group = gtk_radio_button_group (GTK_RADIO_BUTTON (other_button));
  gtk_widget_set_name (other_button, "other_button");
  gtk_widget_ref (other_button);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "other_button", other_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (other_button);
  gtk_table_attach (GTK_TABLE (table4), other_button, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (other_button, GTK_CAN_FOCUS);

  label161 = gtk_label_new (_("Point Type"));
  gtk_widget_set_name (label161, "label161");
  gtk_widget_ref (label161);
  gtk_object_set_data_full (GTK_OBJECT (edit_entry), "label161", label161,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label161);
  gtk_table_attach (GTK_TABLE (table4), label161, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label161), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label161), 9, 0);

  gtk_signal_connect (GTK_OBJECT (close_edit_element), "clicked",
                      GTK_SIGNAL_FUNC (on_close_edit_entry_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (update_element_button), "clicked",
                      GTK_SIGNAL_FUNC (on_update_element_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry1), "key_press_event",
                      GTK_SIGNAL_FUNC (on_update_element_keypress),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry2), "key_press_event",
                      GTK_SIGNAL_FUNC (on_update_element_keypress),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry3), "key_press_event",
                      GTK_SIGNAL_FUNC (on_update_element_keypress),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry4), "key_press_event",
                      GTK_SIGNAL_FUNC (on_update_element_keypress),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry5), "key_press_event",
                      GTK_SIGNAL_FUNC (on_update_element_keypress),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (edit_entry6), "key_press_event",
                      GTK_SIGNAL_FUNC (on_update_element_keypress),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (binary_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Binary_Button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (integer_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Integer_Button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (unsigned_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Unsigned_Button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (float_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Float_Button_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (other_button), "toggled",
                      GTK_SIGNAL_FUNC (on_Other_Button_toggled),
                      NULL);

  gtk_widget_grab_focus (edit_entry1);
  gtk_widget_grab_default (edit_entry1);
  gtk_object_set_data (GTK_OBJECT (edit_entry), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (edit_entry), accel_group);

  return edit_entry;
}

GtkWidget*
create_add_module (void)
{
  GtkWidget *add_module;
  GtkWidget *table5;
  GtkWidget *label171;
  GtkWidget *label172;
  GtkWidget *label173;
  GtkWidget *add_module_name;
  GtkWidget *add_module_path;
  GtkWidget *add_module_parameters;
  GtkWidget *module_browse_button;
  GtkWidget *module_close;
  GtkWidget *module_add;
  GtkWidget *module_help;

  add_module = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (add_module, "add_module");
  gtk_object_set_data (GTK_OBJECT (add_module), "add_module", add_module);
  gtk_window_set_title (GTK_WINDOW (add_module), _("Module List Editor"));
  gtk_window_set_position (GTK_WINDOW (add_module), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (add_module), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (add_module), 500, -1);

  table5 = gtk_table_new (4, 3, FALSE);
  gtk_widget_set_name (table5, "table5");
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (add_module), table5);

  label171 = gtk_label_new (_("Module Name"));
  gtk_widget_set_name (label171, "label171");
  gtk_widget_ref (label171);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "label171", label171,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label171);
  gtk_table_attach (GTK_TABLE (table5), label171, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label171), 0, 0.5);

  label172 = gtk_label_new (_("Path"));
  gtk_widget_set_name (label172, "label172");
  gtk_widget_ref (label172);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "label172", label172,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label172);
  gtk_table_attach (GTK_TABLE (table5), label172, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label172), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label172), 0, 0.5);

  label173 = gtk_label_new (_("Additional Parameters:"));
  gtk_widget_set_name (label173, "label173");
  gtk_widget_ref (label173);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "label173", label173,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label173);
  gtk_table_attach (GTK_TABLE (table5), label173, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label173), 0, 0.5);

  add_module_name = gtk_entry_new ();
  gtk_widget_set_name (add_module_name, "add_module_name");
  gtk_widget_ref (add_module_name);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "add_module_name", add_module_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add_module_name);
  gtk_table_attach (GTK_TABLE (table5), add_module_name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  add_module_path = gtk_entry_new ();
  gtk_widget_set_name (add_module_path, "add_module_path");
  gtk_widget_ref (add_module_path);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "add_module_path", add_module_path,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add_module_path);
  gtk_table_attach (GTK_TABLE (table5), add_module_path, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  add_module_parameters = gtk_entry_new ();
  gtk_widget_set_name (add_module_parameters, "add_module_parameters");
  gtk_widget_ref (add_module_parameters);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "add_module_parameters", add_module_parameters,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add_module_parameters);
  gtk_table_attach (GTK_TABLE (table5), add_module_parameters, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  module_browse_button = gtk_button_new_with_label (_("Browse..."));
  gtk_widget_set_name (module_browse_button, "module_browse_button");
  gtk_widget_ref (module_browse_button);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "module_browse_button", module_browse_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_browse_button);
  gtk_table_attach (GTK_TABLE (table5), module_browse_button, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  GTK_WIDGET_UNSET_FLAGS (module_browse_button, GTK_CAN_FOCUS);

  module_close = gtk_button_new_with_label (_("Close"));
  gtk_widget_set_name (module_close, "module_close");
  gtk_widget_ref (module_close);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "module_close", module_close,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_close);
  gtk_table_attach (GTK_TABLE (table5), module_close, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  module_add = gtk_button_new_with_label (_("Accept"));
  gtk_widget_set_name (module_add, "module_add");
  gtk_widget_ref (module_add);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "module_add", module_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_add);
  gtk_table_attach (GTK_TABLE (table5), module_add, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  module_help = gtk_button_new_with_label (_("Help"));
  gtk_widget_set_name (module_help, "module_help");
  gtk_widget_ref (module_help);
  gtk_object_set_data_full (GTK_OBJECT (add_module), "module_help", module_help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (module_help);
  gtk_table_attach (GTK_TABLE (table5), module_help, 2, 3, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  gtk_signal_connect (GTK_OBJECT (add_module_name), "key_press_event",
                      GTK_SIGNAL_FUNC (module_editor_key_press),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (add_module_path), "key_press_event",
                      GTK_SIGNAL_FUNC (module_editor_key_press),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (add_module_parameters), "key_press_event",
                      GTK_SIGNAL_FUNC (module_editor_key_press),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (module_browse_button), "clicked",
                      GTK_SIGNAL_FUNC (on_module_browse_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (module_close), "clicked",
                      GTK_SIGNAL_FUNC (on_module_close_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (module_add), "clicked",
                      GTK_SIGNAL_FUNC (on_module_accept_clicked),
                      NULL);

  gtk_widget_grab_focus (add_module_name);
  return add_module;
}

