/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_top_level (void);
GtkWidget* create_About (void);
GtkWidget* create_Add_Element (void);
GtkWidget* create_reuse_error (void);
GtkWidget* create_fileselection1 (void);
GtkWidget* create_Notebook_Popup (void);
GtkWidget* create_edit_entry (void);
GtkWidget* create_add_module (void);
